name: Socrata Refresh Stats

#username StrawberryToastLosAngeles

on:
  push:
    branches:
      - master
      - main

  schedule:
    - cron: '0,15,30,45 * * * *'

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Show directory
        run: ls -a

      - name: Show path
        run: pwd

      - name: Fetch from Socrata
        run: node scripttofetchtimeofupdate.js

      - name: Delete extra files
        run: rm -rf tempfile-*

      - name: Commit files
        env: # Or as an environment variable
          GITTOKEN: ${{ secrets.SOCRATAAUTOGIT }}
        run: |-
          git config --local user.name StrawberryToastLosAngeles
          git config --local user.email "126627495+StrawberryToastLosAngeles@users.noreply.github.com"
          if ! git diff --exit-code; then
              git add .
              git commit -am "Updating Socrata Autofetch $(date)"
              git remote set-url origin
              git push -f https://$GITTOKEN:$GITTOKEN@github.com/LosAngelesController/controller-website.git main
          fi
